// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Mpesa Vending Machine

#ifndef _UI_COMP_IMG_QR_CODE_H
#define _UI_COMP_IMG_QR_CODE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT IMG QR Code
#define UI_COMP_IMG_QR_CODE_IMG_QR_CODE 0
#define _UI_COMP_IMG_QR_CODE_NUM 1
lv_obj_t * ui_IMG_QR_Code_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
