// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Mpesa Vending Machine

#include "../ui.h"


// COMPONENT IMG QR Code

lv_obj_t * ui_IMG_QR_Code_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_IMG_QR_Code;
    cui_IMG_QR_Code = lv_img_create(comp_parent);
    lv_img_set_src(cui_IMG_QR_Code, &ui_img_img_qr_png);
    lv_obj_set_width(cui_IMG_QR_Code, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_IMG_QR_Code, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_IMG_QR_Code, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_IMG_QR_Code, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_IMG_QR_Code, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(cui_IMG_QR_Code, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_IMG_QR_Code, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_IMG_QR_Code, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(cui_IMG_QR_Code, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(cui_IMG_QR_Code, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(cui_IMG_QR_Code, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMG_QR_CODE_NUM);
    children[UI_COMP_IMG_QR_CODE_IMG_QR_CODE] = cui_IMG_QR_Code;
    lv_obj_add_event_cb(cui_IMG_QR_Code, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_IMG_QR_Code, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_IMG_QR_Code_create_hook(cui_IMG_QR_Code);
    return cui_IMG_QR_Code;
}

