// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Mpesa Vending Machine

#ifndef _MPESA_VENDING_MACHINE_UI_COMP_HOOK_H
#define _MPESA_VENDING_MACHINE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_IMG_QR_Code_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
